# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: power users
email: durukan.emre93@gmail.com
description: >
  kişisel blog
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emredurukn.github.io" # the base hostname & protocol for your site
paginate:	7 # The number of posts to show per page on your homepage
disqus_name: power-users

name: 'Emre Durukan'
bio: >
  Teknoloji Meraklısı
author_image: "/assets/images/author.jpg"
twitter_username: emredurukn
github_username:  emredurukn

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
